# src/agents/loop_agent.py
import asyncio
from ..memory.memory_store import MemoryStore
from ..utils import timestamp

class LoopAgent:
    """
    Long-running loop agent that periodically checks mem/ for meetings without 'followed_up'
    and simulates a follow-up/reminder action. Demonstrates long-running operations.
    Use `run_forever()` in an async context (or run it in a separate thread/process).
    """
    def __init__(self, interval_seconds: int = 30):
        self.interval = interval_seconds
        self.mem = MemoryStore()

    async def run_forever(self):
        print("[LoopAgent] started run_forever loop (interval {}s)".format(self.interval))
        while True:
            try:
                meetings = self.mem.list_meetings()
                for fname in meetings:
                    # fname includes the .json extension; strip it for meeting_id
                    meeting_id = fname.replace(".json", "")
                    data = self.mem.load_meeting(meeting_id)
                    if not data:
                        continue

                    # If we haven't added a follow-up marker, add one and save
                    if not data.get("followed_up"):
                        data["followed_up"] = True
                        data.setdefault("reminders", []).append({
                            "at": timestamp(),
                            "note": "Auto follow-up generated by LoopAgent"
                        })
                        self.mem.store_meeting(meeting_id, data)
                        print(f"[LoopAgent] added follow-up for {meeting_id}")
            except Exception as e:
                # never crash the loop; log error and continue
                print(f"[LoopAgent] encountered error: {e}")
            await asyncio.sleep(self.interval)
